### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by bhuann** [bhuann/ICT2101-p3-07#1]
[https://www.google.com/url?q=https://lucid.app/lucidchart/3bed2354-a975-4b11-a197-2593572fdeda/edit?viewport_loc%3D53%252C-207%252C1765%252C768%252C0_0%26invitationId%3Dinv_e8b5f8f8-8d18-411e-aba5-2bec1b0f93f7%23&sa=D&source=docs&ust=1663686651070027&usg=AOvVaw1ET-ELt-jJHffNQFqXKHAT](https://lucid.app/lucidchart/3bed2354-a975-4b11-a197-2593572fdeda/edit?viewport_loc=53%2C-207%2C1765%2C768%2C0_0&invitationId=inv_e8b5f8f8-8d18-411e-aba5-2bec1b0f93f7#)

**Comment by NoorFathimaa** [comment]
![Image](https://user-images.githubusercontent.com/44317222/191640779-5a78e077-a3cd-42df-9dff-4b320e10a13a.png)
