### ISSUE TITLE
Use case description

### ISSUE THREAD

**Issue by bhuann** [bhuann/ICT2101-p3-07#11]
The link provided below documented the use case description of our project

**Comment by NoorFathimaa** [comment]
https://docs.google.com/document/d/1ZfLa0gHxlhc80LQ-uNGImr0oxJ3-nHHUubiu9TjggbQ/edit?usp=sharing

**Comment by bhuann** [comment]
![Image](https://user-images.githubusercontent.com/92810012/195612754-e024968b-efec-4aa0-b5c6-be18519d18ae.png)



![Image](https://user-images.githubusercontent.com/92810012/195612811-262cc7f2-d96a-40ba-bbc2-67fb108fc688.png)



![Image](https://user-images.githubusercontent.com/92810012/195612856-e660235d-9973-4c9f-8ca8-88c275828f6b.png)




![Image](https://user-images.githubusercontent.com/92810012/195612900-a1957dbf-ff0d-4db0-a5c9-0907e74e52e8.png)



![Image](https://user-images.githubusercontent.com/92810012/195612955-294e7f3e-9771-438b-8723-11f75bc76eda.png)



![Image](https://user-images.githubusercontent.com/92810012/195613106-ad3c7cb6-bf09-42da-a3f3-553f57250f76.png)



![Image](https://user-images.githubusercontent.com/92810012/195613142-db8c2274-9ee7-451e-84ff-9579b4e4308d.png)



![Image](https://user-images.githubusercontent.com/92810012/195613195-a91f35fc-baf5-473d-af1f-3dfa91bb6f10.png)



![Image](https://user-images.githubusercontent.com/92810012/195613250-ea61eca2-b7c4-4cd4-9529-c974a010e6fa.png)



![Image](https://user-images.githubusercontent.com/92810012/195613362-935dffa5-dc53-4c99-8a35-056ed7cef637.png)



![Image](https://user-images.githubusercontent.com/92810012/195613419-4e5f7239-3a46-4289-b948-5abc83e19ab7.png)



![Image](https://user-images.githubusercontent.com/92810012/195613466-7cf814cc-8a3d-4e25-8901-23efe3befd54.png)



![Image](https://user-images.githubusercontent.com/92810012/195613512-28c45ae5-4b5b-4397-b0f6-19a90d811c76.png)



![Image](https://user-images.githubusercontent.com/92810012/195613571-dfdbf8fe-0af7-4442-921f-e24709968b02.png)
