### ISSUE TITLE
Create low-fi prototype UI

### ISSUE THREAD

**Issue by bhuann** [bhuann/ICT2101-p3-07#13]
The low-fi wireframe prototypes of the website UI are created

- [x] Login page (Manager)
- [x] Login page (Staff)
- [x] Login page (IT Administrator)
- [x] Manager Landing page 
- [x] Staff Landing page
- [x] IT Administrator Landing page
- [x] Manager Job Allocation page
- [x] View Job Calendar
- [x] Add Job Availability Form
- [x] Reject Job Allocation

**Comment by NoorFathimaa** [comment]
https://www.google.com/url?q=https://miro.com/welcomeonboard/U1lIZXYyeW9DOXdwdlR5U0RmbHFXakptTVplcFQ5TjRlbDJaa3VvcTZlVUYxOVBKWjQxMnBHUTdUNHNHNmdWcnwzNDU4NzY0NTMzMjY2NTU5ODM2fDI%3D?share_link_id%3D48778642637&sa=D&source=docs&ust=1663811954592187&usg=AOvVaw2keqtAMaP_qcICc4pQffnI

**Comment by bhuann** [comment]
![Image](https://user-images.githubusercontent.com/92810012/195615768-cc1058b1-46ef-4626-b308-bd5b00c6a0b0.png)



![Image](https://user-images.githubusercontent.com/92810012/195615820-fdf8ef86-d750-4da7-96d7-58bb33ca8ff7.png)



![Image](https://user-images.githubusercontent.com/92810012/195615880-6d258782-5543-4b8f-8604-95b28a867245.png)



![Image](https://user-images.githubusercontent.com/92810012/195615929-078d61fb-ffda-4d7f-bdae-fb9bef781e09.png)



![Image](https://user-images.githubusercontent.com/92810012/195615966-c436cda2-bba7-43ef-9117-42617a571353.png)



![Image](https://user-images.githubusercontent.com/92810012/195616015-6bf129df-cb8c-404d-8c84-cdf2c4e810d8.png)



![Image](https://user-images.githubusercontent.com/92810012/195616059-e59c61ca-d3f4-44b2-8ec4-acc9229bdc83.png)



![Image](https://user-images.githubusercontent.com/92810012/195616103-fb3a9c4c-0e34-4654-97b6-e3ae5e662f2f.png)



![Image](https://user-images.githubusercontent.com/92810012/195616143-624e9725-b45d-4c84-a2cc-40e635528162.png)
