### ISSUE TITLE
Refining Prototype Wireframe

### ISSUE THREAD

**Issue by NoorFathimaa** [bhuann/ICT2101-p3-07#40]
Refined Wireframe:

- sort hours accordingly and highlight those that have more than 40hrs of work
- added instruments
- added studio availability

**Comment by hengwej** [comment]
![Image](https://user-images.githubusercontent.com/94733758/196846532-8e1cb0d3-e323-499c-b3d1-28156e9567e8.png)

- [ ] Samantha
- [ ] Fathima
- [ ] Baohuan
