### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by hengwej** [bhuann/ICT2101-p3-07#42]

**Comment by NoorFathimaa** [comment]
https://miro.com/app/board/uXjVPQtqWaE=/

**Comment by NoorFathimaa** [comment]
To create a class diagram with all entities, controllers, and interfaces used in the project with the relevant relationships between them. 
Waiting for approval: 
- [ ] Bao Huan 
- [ ] Samantha
- [ ] Jean
