### ISSUE TITLE
White Box Testing

### ISSUE THREAD

**Issue by bhuann** [bhuann/ICT2101-p3-07#68]
- [x] PseudoCode 
- [x] Construct a GFG for the selected method
- [x]  Write Test Cases which will provide 100% coverage for that method

Start date: 12/11/2022
End date: 17/11/2022
Duration (days): 5 days

**Comment by NoorFathimaa** [comment]
**PseudoCode** 

![Image](https://user-images.githubusercontent.com/44317222/202347421-cfc2436c-d4e4-4e9f-b5bb-6c62e513fd09.png)

**Comment by hengwej** [comment]
Control Flow Graph


![Image](https://user-images.githubusercontent.com/94733758/202348156-3e154ec1-f527-4c73-9cbc-86ad7bc0bb57.png)

**Comment by NoorFathimaa** [comment]
![Image](https://user-images.githubusercontent.com/44317222/204071071-92306be8-f9da-4419-86db-a63340783ad6.png)
